export const SETTINGS_COPY = {
  account: '계정',
  app: '앱',
  username: '아이디',
  displayName: '표시 이름',
  storeName: '매장명',
  changePassword: '비밀번호 변경',
  version: '버전',
  build: (version: string, build: string | null) =>
    build ? `${version} (빌드 ${build})` : version,
  updateCheck: '업데이트 확인',
  updateDisabled: '개발 빌드에서는 확인할 수 없어요',
  updateChecking: '확인 중…',
  updateDownloading: '새 버전을 받는 중…',
  updatePending: '새 버전을 받았어요 · 눌러서 다시 시작',
  updateAvailable: '새 버전이 있어요 · 눌러서 받기',
  updateNever: '눌러서 확인',
  lastChecked: (at: string) => `마지막 확인 ${at}`,
  upToDate: '최신 버전을 사용하고 있어요',
  downloaded: '새 버전을 받았어요. 업데이트 확인을 눌러 다시 시작하세요',
  updateFailed: '업데이트를 확인하지 못했어요. 잠시 뒤 다시 시도해 주세요',
  permission: '알림 권한',
  permissionDescription: '새 주문·새 문의 푸시 알림',
  granted: '허용',
  denied: '거부',
  openSettings: '설정 열기',
  logout: '로그아웃',
  logoutTitle: '로그아웃할까요?',
  logoutDescription: '이 기기의 로그인 정보가 삭제되고\n새 주문·문의 푸시 알림을 받지 않아요',
  contact: '문의 help@caquick.kr',
};
